name: Build project

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for StandaloneOSX
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache artifacts
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-StandaloneOSX
          restore-keys: Library-
      - name: Build Unity project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneOSX
      - name: Compress a build artifact
        run: tar -cvf StandaloneOSX.tar -C build StandaloneOSX
      - name: Upload a build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build-StandaloneOSX
          path: StandaloneOSX.tar